Class {
	#name : 'MockedAllocatedClass',
	#superclass : 'Object',
	#category : 'PathSensitivePretenuring-Tests',
	#package : 'PathSensitivePretenuring-Tests'
}

{ #category : 'automatically-generated' }
MockedAllocatedClass class >> fafa [

   ^ self fifi
]

{ #category : 'automatically-generated' }
MockedAllocatedClass class >> fifi [

   ^ self new
]

{ #category : 'automatically-generated' }
MockedAllocatedClass class >> toto [

   ^ self fafa
]
