Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_478207323_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_926851678_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_978790393_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
