Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_619790590_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_666715608_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Association class >> _pretenured_865384320_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
