Extension { #name : 'FM3Element' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_369319273_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_609011553_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_849575263_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]
