Extension { #name : 'FM3Element' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_14862333_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_197929401_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_216805386_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_272250200_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_514606128_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_580976559_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_586234953_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_598252678_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_629049299_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_644369204_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_663356878_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_724346272_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_817898440_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_856466040_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FM3Element class >> _pretenured_885471992_named: aString [

	^ self newTenured
		  name: aString;
		  yourself
]
