Extension { #name : 'FMDanglingReference' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FMDanglingReference class >> _pretenured_214226415_with: aFutureAttribute [

	^ self newTenured
		  parentProperty: aFutureAttribute;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FMDanglingReference class >> _pretenured_487301992_with: aFutureAttribute [

	^ self newTenured
		  parentProperty: aFutureAttribute;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FMDanglingReference class >> _pretenured_511673698_with: aFutureAttribute [

	^ self newTenured
		  parentProperty: aFutureAttribute;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FMDanglingReference class >> _pretenured_596287133_with: aFutureAttribute [

	^ self newTenured
		  parentProperty: aFutureAttribute;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
FMDanglingReference class >> _pretenured_741121581_with: aFutureAttribute [

	^ self newTenured
		  parentProperty: aFutureAttribute;
		  yourself
]
