Extension { #name : 'Margin' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Margin class >> _pretenured_377025202_fromNumber: aNumber [
	"Create a margin whose four values are the same and based on anInteger"

	^ self newTenured
		  fromNumber: aNumber;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Margin class >> _pretenured_42857206_fromNumber: aNumber [
	"Create a margin whose four values are the same and based on anInteger"

	^ self newTenured
		  fromNumber: aNumber;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Margin class >> _pretenured_59634015_fromNumber: aNumber [
	"Create a margin whose four values are the same and based on anInteger"

	^ self newTenured
		  fromNumber: aNumber;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Margin class >> _pretenured_78936027_fromNumber: aNumber [
	"Create a margin whose four values are the same and based on anInteger"

	^ self newTenured
		  fromNumber: aNumber;
		  yourself
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Margin class >> _pretenured_976226452_fromNumber: aNumber [
	"Create a margin whose four values are the same and based on anInteger"

	^ self newTenured
		  fromNumber: aNumber;
		  yourself
]
