Extension { #name : 'Morph' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_14862333_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_14862333_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_181569921_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_181569921_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_185274622_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_185274622_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_197929401_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_197929401_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_214226415_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_214226415_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_216805386_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_216805386_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_235308634_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_235308634_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_272250200_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_272250200_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_298788643_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_298788643_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_334854594_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_334854594_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_374312683_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_374312683_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_377025202_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_377025202_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_425133860_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_425133860_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_493872445_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_493872445_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_511673698_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_511673698_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_586234953_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_586234953_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_589711188_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_589711188_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_596287133_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_596287133_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_59634015_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_59634015_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_598252678_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_598252678_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_622032310_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_622032310_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_629049299_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_629049299_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_644369204_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_644369204_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_724346272_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_724346272_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_78936027_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_78936027_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_826166773_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_826166773_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_917924231_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_917924231_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_931406887_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_931406887_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_939570886_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_939570886_setProperty: aSymbol
		toValue: anObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
Morph >> _pretenured_942260915_setProperty: aSymbol toValue: anObject [
	"change the receiver's property named aSymbol to anObject"

	anObject ifNil: [ ^ self removeProperty: aSymbol ].
	self assureExtension
		_pretenured_942260915_setProperty: aSymbol
		toValue: anObject
]
