Extension { #name : 'MorphExtension' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_14862333_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_14862333_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_14862333_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_181569921_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_181569921_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_181569921_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_185274622_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_185274622_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_185274622_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_197929401_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_197929401_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_197929401_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_214226415_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_214226415_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_214226415_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_216805386_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_216805386_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_216805386_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_235308634_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_235308634_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_235308634_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_272250200_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_272250200_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_272250200_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_298788643_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_298788643_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_298788643_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_334854594_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_334854594_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_334854594_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_374312683_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_374312683_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_374312683_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_377025202_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_377025202_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_377025202_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_425133860_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_425133860_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_425133860_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_493872445_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_493872445_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_493872445_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_511673698_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_511673698_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_511673698_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_586234953_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_586234953_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_586234953_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_589711188_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_589711188_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_589711188_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_596287133_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_596287133_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_596287133_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_59634015_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_59634015_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_59634015_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_598252678_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_598252678_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_598252678_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_622032310_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_622032310_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_622032310_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_629049299_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_629049299_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_629049299_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_644369204_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_644369204_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_644369204_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_724346272_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_724346272_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_724346272_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_78936027_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_78936027_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_78936027_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_826166773_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_826166773_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_826166773_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_917924231_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_917924231_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_917924231_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_931406887_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_931406887_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_931406887_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_939570886_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_939570886_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_939570886_assureOtherProperties
		at: aSymbol
		put: abObject
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_942260915_assureOtherProperties [
	"creates an otherProperties for the receiver if needed"

	^ otherProperties ifNil: [
		  otherProperties := SmallIdentityDictionary newTenured ]
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
MorphExtension >> _pretenured_942260915_setProperty: aSymbol toValue: abObject [
	"change the receiver's property named aSymbol to anObject"

	self _pretenured_942260915_assureOtherProperties
		at: aSymbol
		put: abObject
]
