Extension { #name : 'ProgressBarMorph' }

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_14862333_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_14862333_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_181569921_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_181569921_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_185274622_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_185274622_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_197929401_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_197929401_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_214226415_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_214226415_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_216805386_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_216805386_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_235308634_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_235308634_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_272250200_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_272250200_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_298788643_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_298788643_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_334854594_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_334854594_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_374312683_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_374312683_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_377025202_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_377025202_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_425133860_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_425133860_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_493872445_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_493872445_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_511673698_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_511673698_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_586234953_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_586234953_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_589711188_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_589711188_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_596287133_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_596287133_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_59634015_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_59634015_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_598252678_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_598252678_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_622032310_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_622032310_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_629049299_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_629049299_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_644369204_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_644369204_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_724346272_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_724346272_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_78936027_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_78936027_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_826166773_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_826166773_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_917924231_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_917924231_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_931406887_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_931406887_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_939570886_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_939570886_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> _pretenured_942260915_barFillStyle: aFillStyle [
	"Set the fillStyle for the bar."

	^ self
		  _pretenured_942260915_setProperty: #barFillStyle
		  toValue: aFillStyle
]

{ #category : '*PathSensitivePretenuring-Moose-LocationOfNew' }
ProgressBarMorph >> initialize [
	"Initialize the receiver from the current theme."

	super initialize.
	value := 0.
	start := 0.
	end := 100.
	height := DefaultHeight.
	width := DefaultWidth.
	cachedWidth := 0.
	self
		fillStyle: self theme progressBarFillColor;
		borderStyle: self theme progressBarBorderStyle;
		_pretenured_589711188_barFillStyle:
			self theme progressBarProgressFillColor;
		extent: width @ height + (2 * self borderWidth)
]
