Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Cormas-LocationOfNew' }
Association class >> _pretenured_66341860_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Cormas-LocationOfNew' }
Association class >> _pretenured_779449057_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
