Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Cormas-CallerOfNew' }
Association class >> _pretenured_271742996_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Cormas-CallerOfNew' }
Association class >> _pretenured_342092926_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
