Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Cormas-ApplicationMethod' }
Association class >> _pretenured_382025755_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Cormas-ApplicationMethod' }
Association class >> _pretenured_858844328_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
