Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Microdown-ApplicationMethod' }
Association class >> _pretenured_566281400_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Microdown-ApplicationMethod' }
Association class >> _pretenured_986937019_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
