Extension { #name : 'Association' }

{ #category : '*PathSensitivePretenuring-Moose-CallerOfNew' }
Association class >> _pretenured_327640274_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]

{ #category : '*PathSensitivePretenuring-Moose-CallerOfNew' }
Association class >> _pretenured_499832469_key: newKey value: newValue [
	"Answer an instance of me with the arguments as the key and value of
	the association."

	^ self basicNewTenured key: newKey value: newValue
]
