default_experiment: all
default_data_file: 'experiment.csv'

# a set of suites with different benchmarks and possibly different settings
benchmark_suites:
    DataFrameExecution:
        gauge_adapter: PlainSecondsLog
        command: |-
            eval "%(benchmark)s"
        input_sizes: [1]
        invocations: 30
        benchmarks:
            - "PSPRunner new benchmarkClass: VeritasDataFrame; run"
# a set of executables for the benchmark execution
executors:
    #
    ExecutorBaselineDataFrame:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe/dataframe.image --no-default-preferences"
    ExecutorDataFramePSP:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-psp/dataframe-psp.image --no-default-preferences"
    ExecutorDataFramePSP80:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-psp/dataframe-psp80.image --no-default-preferences"
    ExecutorDataFramePSP70:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-psp70/dataframe-psp70.image --no-default-preferences"
    #
# combining benchmark suites and executions
experiments:
    DataFrame:
        suites:
          - DataFrameExecution
        executions:
          - ExecutorBaselineDataFrame
          - ExecutorDataFramePSP
          - ExecutorDataFramePSP80
          - ExecutorDataFramePSP70