default_experiment: all
default_data_file: 'experiment.csv'

# a set of suites with different benchmarks and possibly different settings
benchmark_suites:
    CormasExecution:
        gauge_adapter: PlainSecondsLog
        command: |-
            eval "%(benchmark)s"
        input_sizes: [1]
        invocations: 30
        benchmarks:
            - "PSPRunner new benchmarkClass: VeritasCormas; run"
    DataFrameExecution:
        gauge_adapter: PlainSecondsLog
        command: |-
            eval "%(benchmark)s"
        input_sizes: [1]
        invocations: 30
        benchmarks:
# a set of executables for the benchmark execution
executors:
    ExecutorBaselineCormas:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./cormas/cormas.image --no-default-preferences"
    ExecutorCormasApplicationMethod:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./cormas-applicationMethod/cormas-applicationMethod.image --no-default-preferences"
    ExecutorCormasLocationOfNew:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./cormas-locationOfNew/cormas-locationOfNew.image --no-default-preferences"
    ExecutorCormasPSP:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./cormas-psp/cormas-psp.image --no-default-preferences"
    ExecutorCormasPSP70:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./cormas-psp70/cormas-psp70.image --no-default-preferences"
    #
    ExecutorBaselineDataFrame:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe/dataframe.image --no-default-preferences"
    ExecutorDataFrameApplicationMethod:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-applicationMethod/dataframe-applicationMethod.image --no-default-preferences"
    ExecutorDataFrameLocationOfNew:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-locationOfNew/dataframe-locationOfNew.image --no-default-preferences"
    ExecutorDataFramePSP:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-psp/dataframe-psp.image --no-default-preferences"
    ExecutorDataFramePSP70:
        path: "."
        executable: "reBenchRunner.sh"
        args: "./baseimage/pharo-vm/pharo --headless ./dataframe-psp70/dataframe-psp70.image --no-default-preferences"
    #
# combining benchmark suites and executions
experiments:
    Cormas:
        suites:
          - CormasExecution
        executions:
          - ExecutorBaselineCormas
          - ExecutorCormasApplicationMethod
          - ExecutorCormasLocationOfNew
          - ExecutorCormasPSP
          - ExecutorCormasPSP70
    #
    DataFrame:
        suites:
          - DataFrameExecution
        executions:
          - ExecutorBaselineDataFrame
          - ExecutorDataFrameApplicationMethod
          - ExecutorDataFrameLocationOfNew
          - ExecutorDataFramePSP
          - ExecutorDataFramePSP70